//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Chats')
export class ChatsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  senderId: number;

  @Column('integer', { nullable: true })
  receiverId: number;

  @Column('text', { nullable: true })
  messageContent: string;

  @Column('date', { nullable: true })
  timestamp: Date;
}
