//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Photos')
export class PhotosEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  photoUrl: string;

  @Column('integer', { nullable: true })
  userId: number;

  @Column('date', { nullable: true })
  uploadDate: Date;
}
