//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('VideoChats')
export class VideoChatsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  callerId: number;

  @Column('integer', { nullable: true })
  receiverId: number;

  @Column('date', { nullable: true })
  startTime: Date;

  @Column('date', { nullable: true })
  endTime: Date;

  @Column('text', { nullable: true })
  status: string;
}
