//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const UsersTitle = () => {
  const record = useRecordContext();
  return <span>Users {record ? `"${record.username}"` : ''}</span>;
};

export const UsersList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <TextField source="username" />
      <EmailField source="email" />
      <ReadOnlyPasswordField source="password" />
      <NumberField source="height" />
      <ReferenceField source="town" reference="townsInZambia" />
      <ReferenceField source="province" reference="provincesInZambia" />
      <TextField source="maritalStatus" />
      <DateField source="dateOfBirth" />
      <TextField source="highestEducation" />
      <BooleanField source="haveKids" />
      <TextField source="lookingFor" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const UsersEdit = () => (
  <Edit title={<UsersTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="username" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="email" />
        </Grid>
        <Grid item xs={4}>
          <PasswordInput source="password" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="height" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="town" reference="townsInZambia" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="province" reference="provincesInZambia" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="maritalStatus" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="dateOfBirth" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="highestEducation" />
        </Grid>
        <Grid item xs={4}>
          <BooleanInput source="haveKids" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="lookingFor" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const UsersCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="username" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="email" />
        </Grid>
        <Grid item xs={4}>
          <PasswordInput source="password" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="height" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="town" reference="townsInZambia" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="province" reference="provincesInZambia" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="maritalStatus" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="dateOfBirth" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="highestEducation" />
        </Grid>
        <Grid item xs={4}>
          <BooleanInput source="haveKids" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="lookingFor" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  ,
  ,
  ,
  <ReferenceInput
    source="town"
    label="town"
    reference="townsInZambia"
    alwaysOn
  />,
  <ReferenceInput
    source="province"
    label="province"
    reference="provincesInZambia"
    alwaysOn
  />,
  ,
  ,
  ,
  ,
  ,
];
