//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const VideoChatsTitle = () => {
  const record = useRecordContext();
  return <span>VideoChats {record ? `"${record.callerId}"` : ''}</span>;
};

export const VideoChatsList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <ReferenceField source="callerId" reference="Users" />
      <ReferenceField source="receiverId" reference="Users" />
      <DateField source="startTime" />
      <DateField source="endTime" />
      <TextField source="status" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const VideoChatsEdit = () => (
  <Edit title={<VideoChatsTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <ReferenceInput source="callerId" reference="Users" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="receiverId" reference="Users" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="startTime" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="endTime" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="status" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const VideoChatsCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <ReferenceInput source="callerId" reference="Users" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="receiverId" reference="Users" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="startTime" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="endTime" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="status" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  <ReferenceInput
    source="callerId"
    label="callerId"
    reference="Users"
    alwaysOn
  />,
  <ReferenceInput
    source="receiverId"
    label="receiverId"
    reference="Users"
    alwaysOn
  />,
  ,
  ,
  ,
];
