//Source code generated by AppGPT (www.appgpt.tech)
import { Admin, Resource, CustomRoutes } from 'react-admin';
import { customDataProvider } from './dataProvider';
import fakeDataProvider from 'ra-data-fakerest';
import { Dashboard } from './dashboard';
import { authProvider, apInitialize } from './authProvider';
import { i18nProvider } from './i18nProvider';
import LoginPage, { Login } from './Login';
import data from './data';
import { UsersList, UsersCreate, UsersEdit } from './resources/Users';
import { PhotosList, PhotosCreate, PhotosEdit } from './resources/Photos';
import { ChatsList, ChatsCreate, ChatsEdit } from './resources/Chats';
import { LikesList, LikesCreate, LikesEdit } from './resources/Likes';
import {
  VideoChatsList,
  VideoChatsCreate,
  VideoChatsEdit,
} from './resources/VideoChats';
import UsersIcon from '@mui/icons-material/AccountCircle';
import PhotosIcon from '@mui/icons-material/Photo';
import ChatsIcon from '@mui/icons-material/Chat';
import LikesIcon from '@mui/icons-material/ThumbUp';
import VideoChatsIcon from '@mui/icons-material/VideoCall';
// SUPERTOKENS
import React from 'react';
import SuperTokens, {
  SuperTokensWrapper,
  getSuperTokensRoutesForReactRouterDom,
} from 'supertokens-auth-react';
import ThirdPartyPasswordless from 'supertokens-auth-react/recipe/thirdpartypasswordless';
import Session from 'supertokens-auth-react/recipe/session';
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';
import * as reactRouterDom from 'react-router-dom';
let sessionFn = Session.init();
SuperTokens.init({
  appInfo: {
    appName: import.meta.env.VITE_SUPERTOKENS_APPNAME,
    apiDomain: import.meta.env.VITE_BACKEND_DOMAIN,
    websiteDomain: import.meta.env.VITE_SUPERTOKENS_WEBSITEDOMAIN,
    apiBasePath: import.meta.env.VITE_BACKEND_APIPATH + '/auth',
    websiteBasePath: import.meta.env.VITE_SUPERTOKENS_WEBSITEBASEPATH,
  },
  recipeList: [
    ThirdPartyPasswordless.init({
      contactMethod: 'EMAIL',
      signInUpFeature: {
        providers: [
          ThirdPartyPasswordless.Github.init(),
          //ThirdPartyPasswordless.Google.init(),
          //ThirdPartyPasswordless.Facebook.init(),
          //ThirdPartyPasswordless.Apple.init(),
        ],
      },
    }),
    sessionFn,
  ],
});
apInitialize(Session);
// END SUPERTOKENS
let dataProvider: any;
if (import.meta.env.VITE_USE_BACKEND_DATA === 'true') {
  dataProvider = customDataProvider(
    import.meta.env.VITE_BACKEND_DOMAIN +
      import.meta.env.VITE_BACKEND_APIPATH +
      '/proxy',
  );
} else {
  dataProvider = fakeDataProvider(data.defaultData);
}

const App = () => (
  <SuperTokensWrapper>
    <BrowserRouter basename="/ae5abcc42">
      <Admin
        authProvider={
          import.meta.env.VITE_ENVIRONMENT != 'DEV' ? authProvider : undefined
        }
        requireAuth
        loginPage={LoginPage}
        dataProvider={dataProvider}
        i18nProvider={i18nProvider}
        dashboard={Dashboard}
      >
        <Resource
          name="Users"
          options={{ label: 'Users' }}
          list={UsersList}
          create={UsersCreate}
          edit={UsersEdit}
          recordRepresentation="username"
          icon={UsersIcon}
        />
        <Resource
          name="Photos"
          options={{ label: 'Photos' }}
          list={PhotosList}
          create={PhotosCreate}
          edit={PhotosEdit}
          recordRepresentation="photoUrl"
          icon={PhotosIcon}
        />
        <Resource
          name="Chats"
          options={{ label: 'Chats' }}
          list={ChatsList}
          create={ChatsCreate}
          edit={ChatsEdit}
          recordRepresentation="messageContent"
          icon={ChatsIcon}
        />
        <Resource
          name="Likes"
          options={{ label: 'Likes' }}
          list={LikesList}
          create={LikesCreate}
          edit={LikesEdit}
          recordRepresentation="userId"
          icon={LikesIcon}
        />
        <Resource
          name="VideoChats"
          options={{ label: 'Video Chats' }}
          list={VideoChatsList}
          create={VideoChatsCreate}
          edit={VideoChatsEdit}
          recordRepresentation="callerId"
          icon={VideoChatsIcon}
        />
        <CustomRoutes noLayout>
          {/*This renders the login UI on the /auth route*/}
          {getSuperTokensRoutesForReactRouterDom(reactRouterDom)}
          {/*Your app routes*/}
        </CustomRoutes>
      </Admin>
    </BrowserRouter>
  </SuperTokensWrapper>
);

export default App;
